### ISSUE TITLE
Web Module not working in 1.15.2 (java.lang.NoClassDefFoundError: spark/Spark)

### ISSUE THREAD

**Issue by ctkoakenleaf** [TheNewEconomy/TNE-Bukkit#391]
#### What is the issue/bug you're experiencing?
Web Module not working on 1.15.2

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Add module to the modules folder and reload
Try and run /tnem l Web

#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9

#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119b

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Web, No.

#### Spigot/Bukkit version?
git-Spigot-8faa8b4-689f429 (MC: 1.15.2)

#### Is your server run in online mode?
Yes

#### The exact command you ran w/ arguments?
See above.

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/3BULqt3S
the web.yml is still set to the defaults.

#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/hMVK9sSr
(the unknown command messages at the end can be ignored. they are due to DiscordSRV not being configured properly)

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

Output of /tne report: https://pastebin.com/KiBz2wG1

**Comment by creatorfromhell** [comment]
The web module is not ready for public use.
